### PR TITLE
Make workflow work better

### PR DESCRIPTION
**Pull request by KTibow**
This makes it publish to release, on release.

### CODE REVIEW

**Comment by KTibow** [comment]
Will we need to put it into `src/`?

**Comment by KTibow** [comment]
Nope, doesn't look like it. Loading great!

**Comment by maykar** [comment]
Yup, it's working perfectly. Nice job!

**Comment by maykar** [comment]
Only 2.09kb after HACS gzip

**Comment by maykar** [comment]
This is a great, super simple way to add babel/uglify to smaller projects that have no need for a bunch of dependencies. Totally stealing this for swipe-navigation and probably some other projects. Thanks for this!

**Pull request merged**
