### PR TITLE
Update kiosk-mode.js

### PR DESCRIPTION
**Pull request by nxarmada**
Removes the Header Title, but keeps the views

### CODE REVIEW

**Comment by matt8707** [comment]
What exactly does this commit fix? I don't see any difference in testing and it basically targets the same element.

header
toolbar

**Comment by KTibow** [comment]
It's for 0.117.

**Comment by matt8707** [comment]
I'm on 0.117 :thinking:

**Comment by KTibow** [comment]
I think it's supposed to make it be hidden except the views still show, eg compact. Maybe this could be configurabke,

**Comment by matt8707** [comment]
I figured that too but I don't see any difference.

**Comment by KTibow** [comment]
On 0.116, it just hides the top part of it (like the buttons and title)

**Comment by matt8707** [comment]
Same on 0.117

**Comment by KTibow** [comment]
If you have multiple tabs, it keeps them.

**Comment by matt8707** [comment]
Not on 0.117 at least, maybe it's because of the new [compact header](https://github.com/home-assistant/frontend/pull/7369).

**Comment by KTibow** [comment]
@matt8707 Maybe read the description:
> Removes the Header Title, but keeps the views

**Comment by nxarmada** [comment]
I have multiple tabs on my tablet for different removes, the Original kiosk hides the tabs (views), my change keeps the tabs (views) visible.  Version of HA is any version that has Lovelace

**Comment by nxarmada** [comment]
Kiosk

**Comment by KTibow** [comment]
I think this should be conditional (try ?compact?instead), but 0.117 introduces native compact header with no way to turn it off.

**Comment by nxarmada** [comment]
This pull request was before the current update of Kiosk, where the previous version hides everything.

**Comment by KTibow** [comment]
Also sorry for being ignorant and not putting two and two together @matt8707

**Comment by nxarmada** [comment]
its clear everyone misses the point LOL....this was also prior 117

**Pull request closed without merging**
