### PR TITLE
Cleanup a bit from last PR

### PR DESCRIPTION
**Pull request by maykar**
Sorry, just a bit of housekeeping on last PR

### CODE REVIEW

**Comment by maykar** [comment]
Removes an unnecessary nested if statement

**Comment by matt8707** [comment]
Now that I have you, do you have any insight how to make the styles stick on dashboard change? 

The closest I've gotten is

```javascript
const path = document
  .querySelector("body > home-assistant")
  .shadowRoot.querySelector("home-assistant-main")
  .shadowRoot.querySelector("app-drawer-layout > partial-panel-resolver");

const callback = function (mutationsList, observer) {
  for (const mutation of mutationsList) {
    if (mutation.type === "childList") {
      // location.reload();
      console.log("dashboard change");
    }
  }
};
const observer = new MutationObserver(callback);
observer.observe(path, { childList: true });
```

**Comment by maykar** [comment]
Why not make it configurable, like, if URL contains a string. That way the user could use the unique part of a dashboards URL to define it. You could then add that to the current URL check function I just added. So like, have the user add config to root like custom header was and do something like this:

```
kiosk_mode:
  hide_header_strings:
    - "dashName1"
    - "dashName2"
  kiosk_mode_strings:
    - "dashName3"
```

Grab the config with something like this: 

```
const config = document.querySelector("home-assistant").shadowRoot.querySelector("home-assistant-main").shadowRoot.querySelector("ha-panel-lovelace").__lovelace.config.kiosk_mode
```

And change the checks to something like this:
```
if (locIncludes(["kiosk", "hide_header"]) || locIncluedes([...config.kiosk_mode_strings, ...config.hide_header_strings])) {
```

**Comment by maykar** [comment]
That would open the possibility for not only whole dashboards, but also anything that has a unique URL. So some views in a dashboard could use any of the options while others wouldn't.

**Comment by maykar** [comment]
While talking about this, there is something that you definitely need to add: a disable option like `?disable_kiosk` or something. Otherwise you're going to start trapping people into dashboards and views.

**Comment by maykar** [comment]
But if you want it to stick without user intervention, look into `window.localStorage`. That way you can store a variable in the browser's cache and retrieve it on every load.

**Comment by maykar** [comment]
Localstorage stores everything as a string so you'll have to keep that in mind for your checks, but you could set and retrieve it with something like:

```
localStorage.setItem('kiosk', 'true')
localStorage.getItem('kiosk')
```

**Pull request merged**
