### PR TITLE
Cache, clear_cache, and disable_kiosk

### PR DESCRIPTION
**Pull request by maykar**
This one will need some explaining in the readme if/when you merge and release.

This adds a cache feature. If you add `cache` to the end of the URL (or anywhere really) it will cache your preferences and will persist between views and dashboards. Example: `?hide_header&cache`. That will make it so that every view and dashboard will hide the header (works for all options).

To help with that new feature there are two more keywords added as well. Putting `?clear_cache` in the URL will clear those cached preferences and adding `?disable_kiosk` will temporarily disable any modification.

### CODE REVIEW

**Comment by maykar** [comment]
I believe that if this is pulled and released along with my last PR, you can close #3, #4, and #5. Also, with the release of HA 0.117 I believe you can close #9 as well. 😄

**Comment by matt8707** [comment]
Yeah, this is a very elegant way of doing it and yes seems to fix every issue 🎉

**Comment by maykar** [comment]
This occurred to me this morning: A nice side effect of this is that you can set your cache per device, so you can do `?hide_header&cache` on one device and `?kiosk&cache` on another.

**Comment by matt8707** [comment]
That is nice, I'll add it to the readme

**Comment by maykar** [comment]
Just added a quick update to fix a bug, thanks for the invite.

Are you on the HA discord? Mind messaging me on there, will be easier to communicate.

**Comment by matt8707** [comment]
I saw that, great! I basically have no time for HA at all right now, new job and other things happening in my life... 
I created this repo because of you archiving CH. You're obviously more fit for this project and I'd be willing to transfer ownership if collab is not enough.

**Comment by maykar** [comment]
Completely up to you, if you want to transfer that's cool, but I'm also totally fine keeping it as is. This project was really enjoyable to fix up for some reason, couldn't stop optimizing/working on it last night, so thanks for indulging my many changes/PRs.

**Comment by maykar** [comment]
I've been thinking of making a collection of sorts of simple projects, like this one, that take portions of features from Custom Header. If it is cool with you, it might be nice to have this transferred over, but I can totally understand if you want to keep it where it is. Just a thought.

**Comment by maykar** [comment]
Or does it make more sense to archive this one and make a new one since this somehow ended up being a complete rewrite (didn't mean to, really. Just wanted to add some improvements, but kind of got out of hand)?

**Comment by matt8707** [comment]
I don’t know how transferred repos are handled in HACS. Do you 🤔? Otherwise I can archive.

> Just wanted to add some improvements, but kind of got out of hand)?

I’m glad you did! ☺️

**Comment by maykar** [comment]
Let's try a transfer and see if it all works out. If not I'll just archive and make a new one. Thanks for this and starting the project, really appreciate it!

**Comment by maykar** [comment]
Seems that worked flawlessly, HACS handled it great, all good! 🥳 

Thanks again!

**Pull request merged**
