### PR TITLE
Add build GitHub Actions

### PR DESCRIPTION
**Pull request by KTibow**
This adds some GitHub actions for building, with babel for old tablet support and uglify.js to reduce your browser load just a bit.

### CODE REVIEW

**Comment by maykar** [comment]
Changed it so that it only runs on release, so things like readme changes or commits that aren't ready to be released don't trigger it. Also, for some reason HACS isn't looking in the dist directory (at least for the last release) when it should do so by default. Talking to ludeeus about it currently.

**Comment by maykar** [comment]
If you get a chance can you attempt some changes on a fork. Move the unmodified js file into `src/kiosk-mode.js` and change up the action to act on that file instead?

I think the issue is that it exists in the root of the directory.

**Comment by KTibow** [comment]
I was able to do that, but I think that the action won't work on release. Once a release is published, it can do nothing. Do you want to make it a [manually-triggered action](https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/)?

**Comment by maykar** [comment]
Nah, I'll see if there's something else we can do. One other option is adding it as a release asset instead with `actions/upload-release-asset@v1`

**Comment by maykar** [comment]
If it helps, this is the custom header action that on release ran it's build scripts, then uploaded the file to the release.

https://github.com/maykar/custom-header/actions/runs/280786562/workflow

I don't know enough about github actions to be of much use here. Ludeeus was kind enough to write that one for me, it's also very similar to the one included in boilerplate card.

**Comment by KTibow** [comment]
Okay, I'll get to work.

**Comment by maykar** [comment]
The file gets added after release, but HACS is fine with that

**Comment by maykar** [comment]
Here's another example:

https://github.com/home-assistant/cli/blob/master/.github/workflows/build.yml#L38****

**Pull request merged**
